#!/bin/csh
#
# print date and time
date
#
#

# Increase memory required and specify number of cores we need
##$ -l mem_free=11G
#$ -q debug
#$ -pe smp 8

module load intel

./driver -bacteria=1 -animate=1 -recFields=1 -start=0 -time=2 \
-rDiff=20.0 -wDiff=50.0 -benefit=8.0 -harm=6.0 -cost=0.0 \
-rSat=0.01 -wSat=0.1 -rSec=40.0 -wSec=0.01 \
-rDec=50.0 -wDec=10.0 -mutProb=2.0 -dSec=4.0 > summary.dat

mkdir Run_Data

mv *.dat Run_Data

# print date and time again
date

## End Job Script ##


